# -*- coding: utf-8 -*-
"""HEALTH MATE .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b3Gpn5G2m1JOTRnTIdJQ9xw1styVGxU5
"""

import re
import json
import os

User_specific_service = ""
Useris_service_history = ""


disease_db = {
    "Influenza": ["fever", "cough", "headache", "muscle pain", "runny nose"],
    "COVID-19": ["fever", "cough", "shortness of breath", "loss of smell", "fatigue"],
    "Common Cold": ["cough", "runny nose", "sneezing", "mild headache"],
    "Malaria": ["fever", "sweating", "chills", "nausea", "headache"],
    "Typhoid": ["fever", "fatigue", "abdominal pain", "constipation", "headache"]
}

def analyze_symptoms(user_input):
    user_symptoms = [symptom.strip().lower() for symptom in user_input.split(",")]
    results = {}

    for disease, disease_symptoms in disease_db.items():
        match_count = 0
        for symptom in user_symptoms:
            if symptom in [s.lower() for s in disease_symptoms]:
                match_count += 1

        if match_count > 0:
            match_percentage = (match_count / len(disease_symptoms)) * 100
            results[disease] = round(match_percentage, 2)

    return results

def mohammed():
    time_slots = ['9:00 AM', '10:00 AM', '11:00 AM', '12:00 PM', '1:00 PM']
    print("Available time slots:", time_slots)
    User_is_time = input("Enter the time you want to book: ")

    if User_is_time in ["9:00 AM", "11:00 AM", "1:00 PM"]:
        print("Well it's time to book your reservation")
        Full_username = input("Enter your full username: ")
        National_number = input("Enter your national ID number: ")
        print(f"Booking Successfully Completed Full Name: {Full_username}, And the national number: {National_number}, and your service name: {User_specific_service}, Day and Date: {Useris_service_history}, Booking Date: {User_is_time}")
    elif User_is_time in ["10:00 AM", "12:00 PM"]:
        print("There are no available slots")
        print("This time is full of reservations and it is not possible to book at this time, so we will show you the times when reservations can be made")
        time_slots1 = ["9:00 AM", "11:00 AM", "1:00 PM"]
        print("Available slots:")
        print("9:00 AM (4 slots available)")
        print("11:00 AM (9 slots available)")
        print("1:00 PM (3 slots available)")
        print(time_slots1)
        Booking_date = input("Enter the time you want to book: ")
        if Booking_date in time_slots1:
            print("Well it's time to book your reservation")
            Full_username = input("Enter your full username: ")
            National_number = input("Enter your national ID number: ")
            print(f"Booking Successfully Completed Full Name: {Full_username}, And the national number: {National_number}, and your service name: {User_specific_service}, Day and Date: {Useris_service_history}, Booking Date: {Booking_date}")
        else:
            print("Invalid time slot selected")
def mamoud():
   time_slots = ['9:00 AM', '10:00 AM', '11:00 AM', '12:00 PM', '1:00 PM']
   print("Available time slots:", time_slots)
   User_is_time = input("Enter the time you want to book: ")

   if User_is_time in ["11:00 AM", "12:00 PM", "1:00 PM"]:
        print("Well it's time to book your reservation")
        Full_username = input("Enter your full username: ")
        National_number = input("Enter your national ID number: ")
        print(f"Booking Successfully Completed Full Name: {Full_username}, And the national number: {National_number}, and your service name: {User_specific_service}, Day and Date: {Useris_service_history}, Booking Date: {User_is_time}")
   elif User_is_time in ["10:00 AM", "9:00 AM"]:
        print("There are no available slots")
        print("This time is full of reservations and it is not possible to book at this time, so we will show you the times when reservations can be made")
        time_slots1 = ["11:00 AM", "12:00 PM", "1:00 PM"]
        print("Available slots:")
        print("9:00 AM (4 slots available)")
        print("11:00 AM (9 slots available)")
        print("1:00 PM (3 slots available)")
        print(time_slots1)
        Booking_date = input("Enter the time you want to book: ")
        if Booking_date in time_slots1:
            print("Well it's time to book your reservation")
            Full_username = input("Enter your full username: ")
            National_number = input("Enter your national ID number: ")
            print(f"Booking Successfully Completed Full Name: {Full_username}, And the national number: {National_number}, and your service name: {User_specific_service}, Day and Date: {Useris_service_history}, Booking Date: {Booking_date}")
        else:
            print("Invalid time slot selected")



def load_users():
    file_name = "users.json"
    if os.path.exists(file_name):
        with open(file_name, "r") as f:
            return json.load(f)
    return {}

def save_users(users):
    with open("users.json", "w") as f:
        json.dump(users, f)

def validate_password(password):
    if len(password) != 8:
        print("The password must contain eight characters")
        return False
    if not re.search(r"[A-Z]", password):
        print("The password must contain at least one capital letter")
        return False
    if not re.search(r"[a-z]", password):
        print("The password must contain at least one lowercase letter")
        return False
    if not password.isalpha():
        print("The password must not contain symbols or numbers (letters only)")
        return False
    return True

def sign_up():
    users = load_users()
    answer_user = input("Choose sign up or login please: ").strip().lower()

    if answer_user == "sign up":
        print("Hello new user")
        user_name = input("Enter your user name: ").strip()

        if user_name in users:
            print("Username already exists, Try another one")
            return

        while True:
            password = input("Enter your password (8 chars, uppercase, lowercase, letters only): ")
            if not validate_password(password):
                print("Weak Password, Please try again.")
                continue

            confirm_password = input("Enter password again: ")
            if password == confirm_password:
                users[user_name] = password
                save_users(users)
                print("Successful Registration")
                break
            else:
                print("Passwords Mismatched, Please Try Again")

    elif answer_user == "login":
        if not users:
            print("No users registered yet, Please sign up first")
            return

        while True:
            print("\nPlease login")
            user_name = input("Enter your user name: ").strip()
            password = input("Enter your password: ").strip()

            if user_name in users and users[user_name] == password:
                print(f"Welcome back, {user_name}")


                print("Welcome to the Smart Symptom Analyzer")
                print("Please enter the symptoms you are experiencing, separated by commas")
                user_input = input("Example: fever, cough, headache ,muscle pain,runny nose ,shortness of breath ,loss of smell,fatigue,sneezing, mild headache, sweating,chills,nausea ,abdominal pain,constipation,\n>> ")

                results = analyze_symptoms(user_input)

                if results:
                    print("\nPossible diseases based on your symptoms:")
                    for disease, percentage in sorted(results.items(), key=lambda x: x[1], reverse=True):
                        print(f"- {disease}: {percentage}% match")

                    most_likely = max(results, key=results.get)
                    print(f"\nMost likely diagnosis: {most_likely}")
                    print("Advice: Please consult a medical professional for an accurate diagnosis.")
                else:
                    print("No matching diseases found. Please try again with different symptoms.")


                answer_user = input("Do you want to book an appointment with a specialist doctor? (yes/no): ").lower()
                if answer_user == "yes":
                    print("Welcome to the reservation system")
                    services = ["mohammed", "mamoud", "hamed", "karrem", "sarah"]
                    print("Available doctors:", services)
                    global User_specific_service
                    User_specific_service = input("Enter the doctor name you want to book: ")

                    days = [
                        "1:18-04-2025, Sunday",
                        "2:19-04-2025, Monday",
                        "3:20-04-2025, Tuesday",
                        "4:21-04-2025, Wednesday",
                        "5:22-04-2025, Thursday"
                    ]
                    print("Available days:", days)
                    global Useris_service_history
                    Useris_service_history = input("Enter the day and date : ")

                    if User_specific_service == "mohammed":
                        mohammed()
                    elif User_specific_service=="mamoud":
                      mamoud()


                break
            else:
                print("Incorrect username or password, Please Try again")
    else:
        print("Unknown choice")


if __name__ == "__main__":
    sign_up()